name: Do something!
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: ${{
          ((github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
          && github.action != 'closed') && (
          !github.event.pull_request.draft
          )
          }}
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - uses: "./"
