name: Do something!
on:
  pull_request:
    types: [labeled, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - if: ${{
          ((github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
          && github.action != 'closed') && (
          contains(github.event.pull_request.labels.*.name, 'pr-testing')
          )
          }}
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - uses: "./"
