name: Do something!
on:
  pull_request:
    types: [ready_for_review]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - if: ${{
          (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
          }}
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - uses: "./"
